### ISSUE TITLE
"-O server" does not work

### ISSUE THREAD

**Issue by rlangus** [jfriesse/omping#41]
In cli.c, the code for op_mode server is commented out.  Also, the man page says there are three modes, but only mentions normal and client modes.  In the work I'm testing, this is the perfect tool, except for the lack of server mode.  Thanks for writing this!

At line 176 in cli.c:
			/*
			 * Temporarily disabled
			 *
			} else if (strcmp(optarg, "server") == 0) {
				*op_mode = OMPING_OP_MODE_SERVER;
			*/

**Comment by jfriesse** [comment]
Hi,
the same issue was filled for fork of omping - https://github.com/troglobit/omping/issues/3. Basically server mode is disabled because of #2 . Sadly I don't have too much time to fix #2, simply because the main reason for omping (corosync using multicast) is no longer relevant, because corosync no longer uses multicast. I was also thinking about implementing proper server with configuration as RFC, what is of course much more work. Anyway, AFAICR as long as every client has unique IP everything should work so just go ahead and uncoment the section.

Closing this issue in favor of #2.

**Comment by rlangus** [comment]
Thanks.
